{
 "title": "Basic Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "WARN logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logback_events_total{level=\"warn\"}"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "logback_events_total{level=\"error\"}"
    }
   ]
  }
 ]
}