server:
  port: 8080

spring:
  application:
    name: social71
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://social71.cre7ho3uz9p0.eu-west-3.rds.amazonaws.com:5432/social71"
    username: social71
    password: social71
    platform: postgres
    hikari:
      connection-test-query: "select 1"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    it:
      digiulio:
        social71: TRACE

springdoc:
  api-docs:
    path: "/v1/api-docs"

---

spring:
  config:
    activate:
      on-profile: localhost
  datasource:
    url: "jdbc:postgresql://postgres-social71:5432/social71"
    username: social71
    password: social71
    platform: postgres