CREATE TABLE USERS (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY,
    USERNAME     VARCHAR(50) NOT NULL,
    PASSWORD     VARCHAR(100) NOT NULL,
    EMAIL        VARCHAR (255) NOT NULL,
    CREATED_ON   TIMESTAMP NOT NULL,
    ACTIVE       BOOLEAN NOT NULL DEFAULT '1',
    DELETE_UUID  VARCHAR(50),

    PRIMARY KEY (ID),
    CONSTRAINT USERS_UNIQUE_USERNAME UNIQUE (USERNAME, ACTIVE, DELETE_UUID),
    CONSTRAINT USERS_UNIQUE_EMAIL    UNIQUE (EMAIL, ACTIVE, DELETE_UUID)
);

CREATE TABLE WHISPERS (
    ID           BIGINT GENERATED ALWAYS AS IDENTITY,
    USER_ID      BIGINT NOT NULL,
    TEXT         VARCHAR(255) NOT NULL,
    CREATED_ON   TIMESTAMP NOT NULL,
    ACTIVE       BOOLEAN NOT NULL DEFAULT '1',

    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);