INSERT INTO users (username, password, email, created_on) values ('antodg', 'passwd', 'antodg95@gmail.com', CURRENT_TIMESTAMP);
INSERT INTO users (username, password, email, created_on) values ('qwerty', 'passwd', 'qwerty@gmail.com', CURRENT_TIMESTAMP);
INSERT INTO users (username, password, email, created_on) values ('asdfg', 'passwd', 'asdfg@gmail.com', CURRENT_TIMESTAMP);
INSERT INTO users (username, password, email, created_on) values ('zxcvb', 'passwd', 'zxcvb@gmail.com', CURRENT_TIMESTAMP);
INSERT INTO users (username, password, email, created_on) values ('poiuy', 'passwd', 'poiuy@gmail.com', CURRENT_TIMESTAMP);
INSERT INTO users (username, password, email, created_on) values ('lkjhg', 'passwd', 'lkjhg@gmail.com', CURRENT_TIMESTAMP);

INSERT INTO whispers(user_id, text, created_on) values (1, 'whisper 1', CURRENT_TIMESTAMP);
INSERT INTO whispers(user_id, text, created_on) values (2, 'whisper 2', CURRENT_TIMESTAMP);
INSERT INTO whispers(user_id, text, created_on) values (3, 'whisper 3', CURRENT_TIMESTAMP);
INSERT INTO whispers(user_id, text, created_on) values (4, 'whisper 4', CURRENT_TIMESTAMP);
INSERT INTO whispers(user_id, text, created_on) values (5, 'whisper 5', CURRENT_TIMESTAMP);
INSERT INTO whispers(user_id, text, created_on) values (6, 'whisper 6', CURRENT_TIMESTAMP);
INSERT INTO whispers(user_id, text, created_on) values (1, 'whisper 7', CURRENT_TIMESTAMP);
INSERT INTO whispers(user_id, text, created_on) values (2, 'whisper 8', CURRENT_TIMESTAMP);
INSERT INTO whispers(user_id, text, created_on) values (3, 'whisper 9', CURRENT_TIMESTAMP);
INSERT INTO whispers(user_id, text, created_on) values (4, 'whisper 10', CURRENT_TIMESTAMP);
INSERT INTO whispers(user_id, text, created_on) values (5, 'whisper 11', CURRENT_TIMESTAMP);
INSERT INTO whispers(user_id, text, created_on) values (6, 'whisper 12', CURRENT_TIMESTAMP);
INSERT INTO whispers(user_id, text, created_on) values (1, 'whisper 13', CURRENT_TIMESTAMP);
INSERT INTO whispers(user_id, text, created_on) values (2, 'whisper 14', CURRENT_TIMESTAMP);