name: develop-action
on:
  push:
    branches:
      - develop
jobs:
  mvn-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run : mvn test