name: first-action
on:
  push:
    branches:
      - develop
jobs:
  mvn-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run : mvn test
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: mvn spring-boot:build-image
      - run: docker image tag social71:${{ steps.project.outputs.version }} antodg95/social71:${{ steps.project.outputs.version }}
      - run: docker push antodg95/social71:${{ steps.project.outputs.version }}