name: first-action
on:
  push:
    branches:
      - develop
jobs:
  mvn-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run : mvn test
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: antodg95/social71:latest